### ISSUE TITLE
System.InvalidOperationException: Sequence contains more than one matching element

### ISSUE THREAD

**Issue by TSteschulat** [unchase/Unchase.OpenAPI.Connectedservice#53]
Hello all,
i get an error while generating c# client:

```
Generating NSwag-file for OpenAPI (Swagger)...
NSwag-file "UnchaseApi.nswag" for OpenAPI (Swagger) was generated.
Generating Client Proxy for OpenAPI (Swagger) Client...
Warning:Error: Error while rendering Liquid template CSharp/Class: 
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at NJsonSchema.CodeGeneration.Models.ClassTemplateModelBase.DerivedClassModel..ctor(String typeName, JsonSchema schema, OpenApiDiscriminator discriminator, TypeResolverBase resolver)
   at NJsonSchema.CodeGeneration.Models.ClassTemplateModelBase.<get_DerivedClasses>b__16_0(KeyValuePair`2 p)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NJsonSchema.CodeGeneration.Models.ClassTemplateModelBase.get_DerivedClasses()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at NJsonSchema.CodeGeneration.LiquidProxyHash.GetValue(String key)
   at DotLiquid.Hash.System.Collections.IDictionary.get_Item(Object key)
   at DotLiquid.Context.LookupAndEvaluate(Object obj, Object key)
   at DotLiquid.Context.FindVariable(String key)
   at DotLiquid.Context.Variable(String markup, Boolean notifyNotFound)
   at DotLiquid.Context.Resolve(String key, Boolean notifyNotFound)
   at DotLiquid.Tags.For.Render(Context context, TextWriter result)
   at DotLiquid.Block.RenderAll(List`1 list, Context context, TextWriter result)
--- End of stack trace from previous location where exception was thrown ---
   at DotLiquid.Context.HandleError(Exception ex)
   at DotLiquid.Block.RenderAll(List`1 list, Context context, TextWriter result)
   at DotLiquid.Tags.If.<>c__DisplayClass11_0.<Render>b__0()
   at DotLiquid.Context.Stack(Hash newScope, Action callback)
   at DotLiquid.Tags.If.Render(Context context, TextWriter result)
   at DotLiquid.Block.RenderAll(List`1 list, Context context, TextWriter result)
--- End of stack trace from previous location where exception was thrown ---
   at DotLiquid.Context.HandleError(Exception ex)
   at DotLiquid.Block.RenderAll(List`1 list, Context context, TextWriter result)
   at DotLiquid.Document.Render(Context context, TextWriter result)
   at DotLiquid.Template.RenderInternal(TextWriter result, RenderParameters parameters)
   at DotLiquid.Template.Render(TextWriter writer, RenderParameters parameters)
   at DotLiquid.Template.Render(RenderParameters parameters)
   at NJsonSchema.CodeGeneration.DefaultTemplateFactory.LiquidTemplate.Render().
Client Proxy for OpenAPI (Swagger) Client was generated.
Re-Adding service instance complete!

```

And it seems that this yaml definition is the source ot it:

```
    JobEvent:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/Uuid4'
        job_id:
          $ref: '#/components/schemas/Uuid4'
        driver_id:
          $ref: '#/components/schemas/Uuid4'
        latitude:
          $ref: '#/components/schemas/GeoCoordinate'
        longitude:
          $ref: '#/components/schemas/GeoCoordinate'
        type:
          enum:
            - on_the_way
            - arrived
            - set_up
            - set_down
            - captured_weightg
            - cashed_up
            - initial_weighed
            - final_weigehd
            - delay
            - status_updated
            - customer_signed
            - position_update
            - message
            - trash_type_changed
            - disposal_plant_changed
            - container_type_changed
            - container_amount_changed
          example: arrived
          description: |
            * on_the_way - driver is on the way to his destination
            * arrived - driver has arrived at his destination
            * set_up - container has been set up
            * set_down - container has been set down
            * captured_weight - weight has been captured by the vehicle
            * cashed_up - payment process has been handeled
            * initial_weighed - initial weight has been taken with load scale
            * final_weighed - weight has been taken with load scale
            * delay - processing delays
            * status_updated - the job status (started, parking ...) has been updated
            * customer_signed - customer has signed
            * message - a message has been sent from the driver app
            * position_updated - driver position update
            * trash_type_changed - driver has changed the trash type
            * disposal_plant_changed - driver has chanegd the disposal plant
            * container_type_changed - driver has changed the container type
            * container_amount_changed - driver has changed the container amount
        created_at:
          $ref: '#/components/schemas/DateTime'
        updated_at:
          $ref: '#/components/schemas/DateTime'
      required:
        - id
        - latitude
        - longitude
        - type
        - created_at
      discriminator:
        propertyName: type
        mapping:
          on_the_way: '#/components/schemas/DrivingJobEvent'
          arrived: '#/components/schemas/DrivingJobEvent'
          set_up: '#/components/schemas/SetContainerJobEvent'
          set_down: '#/components/schemas/SetContainerJobEvent'
          captured_weight: '#/components/schemas/CapturedWeightJobEvent'
          cashed_up: '#/components/schemas/CashedUpJobEvent'
          final_weighed: '#/components/schemas/FinalWeighedJobEvent'
          initial_weighed: '#/components/schemas/InitialWeighedJobEvent'
          delay: '#/components/schemas/DelayJobEvent'
          status_updated: '#/components/schemas/StatusUpdatedJobEvent'
          customer_signed: '#/components/schemas/CustomerSignedJobEvent'
          position_updated: '#/components/schemas/PositionUpdatedJobEvent'
          message: '#/components/schemas/MessageJobEvent'
          trash_type_changed: '#/components/schemas/TrashTypeChangedJobEvent'
          container_type_changed: '#/components/schemas/ContainerTypeChangedJobEvent'
          container_amount_changed: '#/components/schemas/ContainerAmountChangedJobEvent'
          disposal_plant_changed: '#/components/schemas/DisposalPlantChangedJobEvent'

    DrivingJobEvent:
      allOf:
        - $ref: '#/components/schemas/JobEvent'
        - type: object
          properties:
            payload:
              type: object
              properties:
                destination:
                  enum:
                    - customer
                    - disposal_plant
                    - depot
                  description: |
                    * customer - on the way to/arrived at the customer
                    * disposal_plant - on the way to/arrived at the disposal_plant
                    * depot - on the way to/arrived at the depot
              required:
                - destination
          required:
            - paylaod

    SetContainerJobEvent:
      allOf:
        - $ref: '#/components/schemas/JobEvent'
        - type: object
          properties:
            payload:
              type: object
              properties:
                container_id:
                  $ref: '#/components/schemas/Uuid4'
                is_filled:
                  type: boolean
                  example: true
                  description: Is this container filled or empty
              required:
                - container_id
                - is_filled
          required:
            - payload

    CapturedWeightJobEvent:
      allOf:
        - $ref: '#/components/schemas/JobEvent'
        - type: object
          properties:
            playload:
              type: array
              items:
                type: object
                properties:
                  weight:
                    type: number
                    format: float
                    example: 253.5
                    description: Weight in kg.
                required:
                  - weight
          required:
            - paylaod

    CashedUpJobEvent:
      allOf:
        - $ref: '#/components/schemas/JobEvent'
        - type: object
          properties:
            payload:
              type: object
              properties:
                payment_method:
                  enum:
                    - cash
                    - by_card
                    - none
                  description: |
                    * cash - payed cash
                    * by_card - payed by ec or credit card
                    * none - not paid, see additional_info
                  example: cash
                additional_info:
                  type: string
              required:
                - payment_method
          required:
            - payload

    FinalWeighedJobEvent:
      allOf:
        - $ref: '#/components/schemas/JobEvent'
        - type: object
          properties:
            payload:
              type: object
              properties:
                items:
                  type: array
                  minItems: 1
                  maxItems: 6
                  items:
                    type: object
                    properties:
                      weight:
                        type: number
                        format: float
                        example: 2.4
                        description: Weight in tons
                      certificate_number:
                        type: string
                        description: The weighing certificate's number
                        example: NHDBKD-232
                      certificate_image:
                        type: string
                        description: URL to image
                        example: https://xxxxxx-media-provider.de/123e4567-e89b-12d3-a456-426614174000.jpg
                      foreign_weighing:
                        type: boolean
                        example: false
                        description: Has weighing been done by another company?
                    required:
                      - weight
                      - certificate_number
                      - foreign_weighing
              required:
                - items
          required:
            - paylaod

    DelayJobEvent:
      allOf:
        - $ref: '#/components/schemas/JobEvent'
        - type: object
          properties:
            payload:
              type: object
              properties:
                reason:
                  enum:
                    - traffic
                    - pause
                    - waiting
                  example: traffic
                  description: |
                    * traffic - much traffic or traffic jam
                    * pause - driver has set the job to pause
                    * waiting - driver is waiting for something
                additional_info:
                  type: string
                  example: traffic jam in the city
                  description: Optional additional information from driver
                amount:
                  type: integer
                  example: 30
                  description: Amount of delay time in minutes.
              required:
                - reason
                - amount
          required:
            - paylaod

    InitialWeighedJobEvent:
      allOf:
        - $ref: '#/components/schemas/JobEvent'
        - description: Driver has done an initial weighing at the disposal plant.

    StatusUpdatedJobEvent:
      allOf:
        - $ref: '#/components/schemas/JobEvent'
        - type: object
          properties:
            payload:
              type: object
              properties:
                status:
                  enum:
                    - started
                    - resumed
                    - paused
                    - cancelled
                    - finished
                  description: General status info events.
              required:
                - status
          required:
            - paylaod

    TrashTypeChangedJobEvent:
      allOf:
        - $ref: '#/components/schemas/JobEvent'
        - type: object
          properties:
            payload:
              type: object
              properties:
                value:
                  allOf:
                    - $ref: '#/components/schemas/Uuid4'
                    - description: The new trash type.
          required:
            - playload

    DisposalPlantChangedJobEvent:
      allOf:
        - $ref: '#/components/schemas/JobEvent'
        - type: object
          properties:
            payload:
              type: object
              properties:
                value:
                  allOf:
                    - $ref: '#/components/schemas/Uuid4'
                    - description: The new disposal plant.
          required:
            - playload

    ServiceChangedJobEvent:
      allOf:
        - $ref: '#/components/schemas/JobEvent'
        - type: object
          properties:
            payload:
              type: object
              properties:
                value:
                  allOf:
                    - $ref: '#/components/schemas/Uuid4'
                    - description: The new service.
          required:
            - playload

    ContainerTypeChangedJobEvent:
      allOf:
        - $ref: '#/components/schemas/JobEvent'
        - type: object
          properties:
            payload:
              type: object
              properties:
                value:
                  allOf:
                    - $ref: '#/components/schemas/Uuid4'
                    - description: The new container type.
          required:
            - playload

    ContainerAmountChangedJobEvent:
      allOf:
        - $ref: '#/components/schemas/JobEvent'
        - type: object
          properties:
            payload:
              type: object
              properties:
                value:
                  type: integer
                  description: The new container amount.
          required:
            - playload

    PositionUpdatedJobEvent:
      allOf:
        - $ref: '#/components/schemas/JobEvent'
        - description: |
            This event is just to announce the current position and is fired
            regularly in a given interval.

    CustomerSignedJobEvent:
      allOf:
        - $ref: '#/components/schemas/JobEvent'
        - type: object
          properties:
            payload:
              type: object
              properties:
                name:
                  type: string
                  example: John Doe
                  description: Name os signer
                image:
                  type: string
                  example: https://xxxxxx-media-server.de/image-xyz.jpg
                  description: Download URL of customer signature image.

    MessageJobEvent:
      allOf:
        - $ref: '#/components/schemas/JobEvent'
        - type: object
          properties:
            payload:
              $ref: '#/components/schemas/JobMessage'
          required:
            - payload


```

when i delete the "mapping" here:
 mapping:
          on_the_way: '#/components/schemas/DrivingJobEvent'
          arrived: '#/components/schemas/DrivingJobEvent'
          set_up: '#/components/schemas/SetContainerJobEvent'
          set_down: '#/components/schemas/SetContainerJobEvent'
          captured_weight: '#/components/schemas/CapturedWeightJobEvent'
          cashed_up: '#/components/schemas/CashedUpJobEvent'
          final_weighed: '#/components/schemas/FinalWeighedJobEvent'
          initial_weighed: '#/components/schemas/InitialWeighedJobEvent'
          delay: '#/components/schemas/DelayJobEvent'
          status_updated: '#/components/schemas/StatusUpdatedJobEvent'
          customer_signed: '#/components/schemas/CustomerSignedJobEvent'
          position_updated: '#/components/schemas/PositionUpdatedJobEvent'
          message: '#/components/schemas/MessageJobEvent'
          trash_type_changed: '#/components/schemas/TrashTypeChangedJobEvent'
          container_type_changed: '#/components/schemas/ContainerTypeChangedJobEvent'
          container_amount_changed: '#/components/schemas/ContainerAmountChangedJobEvent'
          disposal_plant_changed: '#/components/schemas/DisposalPlantChangedJobEvent'

generation works fine. But thats not the goal of the definition.

Is it a bug or have i done something wrong in the definition?

Regards
Thomas

**Comment by TSteschulat** [comment]
Supplement:

It seems that these 4 entries in the mapping produces the error:

```
          on_the_way: '#/components/schemas/DrivingJobEvent'
          arrived: '#/components/schemas/DrivingJobEvent'
          set_up: '#/components/schemas/SetContainerJobEvent'
          set_down: '#/components/schemas/SetContainerJobEvent'

```
The DrivingJobEvent and SetContainerJobEvent are used twice.
when i delete the "arrived" and "set_down" entries in the mapping the code is generated without an error.
But it seems that it is correct in open api to use schemas more than once even in mappings!? 

Regards
Thomas

**Comment by unchase** [comment]
Hi, @TSteschulat 

The Connected Service based on [NSwag](https://github.com/RicoSuter/NSwag).
Should create the same issue in [this place](https://github.com/RicoSuter/NSwag/issues).
